workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

include:
  - remote: https://arp.to/@ci/docker.yml
  - local: coinbox/jobs.yml
  - local: devel/jobs.yml
  - local: network/jobs.yml
  - local: misc/jobs.yml
